### ISSUE TITLE
Why does it need internet connection?

### ISSUE THREAD

**Issue by rugk** [EmmanuelMess/Simple-Accounting#57]
Such an app would maybe better not request it.

**Comment by EmmanuelMess** [comment]
[ACRA](https://github.com/ACRA/acra), I was thinking of making it optional, but fear people would stop sending error reports if that was the case.

**Comment by rugk** [comment]
Can't you send the crash reports via mail? This is how other apps do it. Then the user can review it and send them…

**Comment by EmmanuelMess** [comment]
Sorry I edited a second ago my answer:

>  Originally ACRA reporting was optional, and via mail, and I only received 2 reports, ever...

**Comment by rugk** [comment]
Hmm… still think considering the subject of this app, and internet permission may not really be the best idea.

**Comment by EmmanuelMess** [comment]
Maybe make it optional, but highly encourage auto-reporting?

**Comment by rugk** [comment]
How do you want to make it optional exactly? The only way to do it is via mail then…

**Comment by EmmanuelMess** [comment]
When the user first starts the app, an explanation would appear, asking to activate auto-reporting, if the user accepts internet permission would be asked for. If a user wants to opt out or in later an option would be available from settings.

**Comment by EmmanuelMess** [comment]
Ok, I didn't know "normal permissions" existed:

> The system's behavior after you declare a permission depends on how sensitive the permission is. Some permissions are considered "normal" so the system immediately grants them upon installation. Other permissions are considered "dangerous" so the user must explicitly grant your app access. For more information about the different kinds of permissions, see [Protection levels](https://developer.android.com/guide/topics/permissions/overview#normal-dangerous). 

-- [source](https://developer.android.com/training/permissions/requesting)

> Normal permissions
> 
> Normal permissions cover areas where your app needs to access data or resources outside the app's sandbox, but where there's very little risk to the user's privacy or the operation of other apps. For example, permission to set the time zone is a normal permission.
>
> If an app declares in its manifest that it needs a normal permission, the system automatically grants the app that permission at install time. The system doesn't prompt the user to grant normal permissions, and users cannot revoke these permissions.
>
> As of Android 8.1 (API level 27), the following permissions are classified as PROTECTION_NORMAL:
> [...]
> * [INTERNET](https://developer.android.com/reference/android/Manifest.permission#INTERNET)
> 
> [...]

-- [source](https://developer.android.com/guide/topics/permissions/overview#permission-groups)

**Comment by EmmanuelMess** [comment]
Ideas?

**Comment by nutpantz** [comment]
I would rather the app asks you to share the error report and send it to the users email client to mail.

**Comment by EmmanuelMess** [comment]
And no one sends me any reports?

**Comment by nutpantz** [comment]
Sadly you can't force people, and without a internet permission it makers people feel safer.. If they can read the mail before it's sent at least the paranoid still might. I just found it on fdroid and I'll send them by email.

**Comment by EmmanuelMess** [comment]
@nutpantz I will see of making two versions.

**Comment by natrius** [comment]
Some apps just ask when opening the app again if you would like to send an error report via e-mail or at all and i can choose if i want or don't want to. 
And second, i am not completely willingly to allow internet to an account app - i blocked it via firewall for most of the apps actually. 

I don't think there is a need for 2 versions.
