### ISSUE TITLE
Proposal new logo for Simple Accounting app

### ISSUE THREAD

**Issue by rezamusic881** [EmmanuelMess/Simple-Accounting#61]
Hi sir, I want to offer a new logo for your simple and sweet app.

You can see the results of my design below, If you like and want to wear them. you simply reply to this proposal, then I will send the file and if you want to request color variations, I am ready to provide it.

![x1](https://user-images.githubusercontent.com/37515077/40937707-b82c29cc-6869-11e8-95f8-f93c8952d2be.png)

**Comment by EmmanuelMess** [comment]
I prefer to follow the [Material Design guidelines](https://material.io/design/iconography/product-icons.html#design-principles). Thanks for your proposal.
