### ISSUE TITLE
Frequently Asked Question (FAQ) and Updated README Proposal 

### ISSUE THREAD

**Issue by olayhemy** [EmmanuelMess/Simple-Accounting#69]
Hello there, I'd like to contribute to your awesome project by providing an Updated ReadMe file and Frequent Asked Questions (FAQ) for users self-service. Would love to hear from you, thanks

**Comment by EmmanuelMess** [comment]
Thanks :smiley:!

Frequent Asked Questions (FAQ)? What questions would those be?
