### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by saifulfrank** [EmmanuelMess/Simple-Accounting#80]
Hi
I want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by EmmanuelMess** [comment]
It seems the current logo is broken on newer android versions, I will have to fix it, if you can fix it I would be very thankful.

**Comment by saifulfrank** [comment]
ok I will fix it. you want to keep the same logo? let me know your expectation.

**Comment by EmmanuelMess** [comment]
The current one seems alright to me...
