### ISSUE TITLE
Restructure repo

### ISSUE THREAD

**Issue by stupidly-logical** [EmmanuelMess/Simple-Accounting#99]
I suggest that the repo is restructured so that the android project comes to the root folder. I'd like to do this @EmmanuelMess

**Comment by EmmanuelMess** [comment]
> I suggest that the repo is restructured so that the android project comes to the root folder. 

Why? Where would the Images folder go?

**Comment by stupidly-logical** [comment]
We can move the images used in the app to the drawbles folder.

**Comment by EmmanuelMess** [comment]
Why? that would unnecessarily slow non-proguarded compilation. Images folder contains the resources used to make the images for the app, not the images themselves.

**Comment by stupidly-logical** [comment]
I think we can exclude files in proguard

**Comment by EmmanuelMess** [comment]
Why would we? Those are needed for updating the resources.

**Comment by stupidly-logical** [comment]
Hmm. Ok.
